### ISSUE TITLE
Two Mistakes in Example in README.md

### ISSUE THREAD

**Issue by dyrenex** [CiscoPSIRT/openVulnAPI#11]
Within the _openVulnAPI/openVulnQuery_ folder the [README.md](https://github.com/CiscoPSIRT/openVulnAPI/blob/master/openVulnQuery/README.md) file has an incorrect example under "**Run OpenVulnQuery as a Libary**". 

Mistakes
---------

The assignment of:

> query_client = query_client.QueryClient(client_id = "", client_secret = "")

Should actually be: 

`query_client = query_client.OpenVulnQueryClient(client_id = '', client_secret = '')`

...due to a change of the object name. 

<enter> 
<enter> 

The line: 

> advisories = query_client.get_by_year(year = 2010, adv_format = "cvrf" parsed_cvrf = True)

Should actually be: 

`advisories = query_client.get_by_year(year=2010, adv_format = 'cvrf', cvrf_parsed = True)`

**Comment by santosomar** [comment]
Thank you! Just saw your pull request and accepted it...
