### ISSUE TITLE
IOS and IOS XE is a combined query - not specific to CVRF of OVAL

### ISSUE THREAD

**Issue by santosomar** [CiscoPSIRT/openVulnAPI#20]
Currently openVulnQuery has the following:

> 
> --ios
>         Search by IOS version
>         Examples:
>         >> openVulnQuery --cvrf --ios 15.6\(2\)SP  (*use \ to escape bracket in ios version)
>         >> openVulnQuery --oval --ios 15.6(\2\)SP

The RESTful URI is not dependent on CVRF or OVAL, it is:
`https://api.cisco.com/security/advisories/ios.json?version=12.4(4)T
`
Perhaps we can consolidate this  to just:

`openVulnQuery --ios 15.6(\2\)SP
`
or 

`openVulnQuery --oval --ios_xe 13.16.1S`

**Comment by iamparas** [comment]
Hello, Omar. The new update resolves above mentioned issue.

**Comment by santosomar** [comment]
Confirmed that the changes in 1.23 has fixed the issue.

https://github.com/CiscoPSIRT/openVulnAPI/pull/30

**Comment by rd101010** [comment]
Hi Omar,
Could we have the openVulnAPI info page on devnet updated with this example. I couldn't get it working until I stumbled upon your posting. There are probably others in the same boat.
https://api.cisco.com/security/advisories/ios.json?version=12.4(4)T
thanks

**Comment by santosomar** [comment]
Hi @rd101010 !

Absolutely! We are currently working on a major update/simplification of the documentation in DevNet. I will add a new issue here to track it. My ETA on getting all documentation ready is by the end of next week. I will keep you posted and will add you to the new issue.
