### ISSUE TITLE
openVulnQuery Client: Change default results to display json by default

### ISSUE THREAD

**Issue by santosomar** [CiscoPSIRT/openVulnAPI#26]
Since the addition of the new fields on the API the table (human readable) is not appropriate anymore. Please change the client to only display the json results from the API. 

The user can still select the fields that want displayed by using the `-f` or `--fields` options. 

```
 [--fields {advisory_id,sir,first_published,last_updated,cves,cvss_base_score,advisory_title,publication_url,cwe,product_names,summary,oval_url,cvrf_url,bug_ids} [{advisory_id,sir,first_published,last_updated,cves,cvss_base_score,advisory_title,publication_url,cwe,product_names,summary,oval_url,cvrf_url,bug_ids} ...]]
```

**Comment by iamparas** [comment]
The new update fixes this issue.
