### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by gadhamak** [CiscoPSIRT/openVulnAPI#44]
Hello.
I was able to install this successfully on a MacBook and work as expected. However, I was not successful installing it on a Linux virtual machine.

Can you please provide guidance or procedure doing this? I could not run a PIP command.

[root@= hamakga]# pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==6.1.1

I have python 2.7.12 and  python 3.6.2 on the machine.

Please help.

**Comment by santosomar** [comment]
Hi,

Can you try the following?
```
sudo /usr/local/bin/pip install --upgrade pip // (to upgrade pip)
sudo /usr/local/bin/pip install virtualenv --upgrade // (to upgrade virtualenv)
```
It appears that it may be a conflict with the version of `pip` you have in the machine. 

If that does not work, please send me the details of your Linux VM such as
```
pip -V
pip3 -V
```
The current version of the client installation via pip only works with pip2 or earlier.

**Comment by santosomar** [comment]
The installation on Linux has been successfully tested in Ubuntu, Kali, Debian, and CentOS. Closing this issue, as we didn't get any additional information from the submitter.
