### ISSUE TITLE
NullPointerException : GET /security/advisories/ios.json

### ISSUE THREAD

**Issue by Ali-aqrabawi** [CiscoPSIRT/openVulnAPI#52]
when i do `GET https://api.cisco.com/security/advisories/ios.json` , get a 500 error with tracebacks in response body : 

</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException
	com.cisco.csc.rest.util.ReleaseParser.removeLeadingZeros(ReleaseParser.java:10)
	com.cisco.csc.rest.controller.OpenVulServiceEndpointImpl.getAdvisoriesIosByVersion(OpenVulServiceEndpointImpl.java:656)
	sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:211)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:243)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:197)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:149)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:211)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by santosomar** [comment]
Not able to reproduce with the latest client. Checked on several machines.
