### ISSUE TITLE
Java example does not include token request

### ISSUE THREAD

**Issue by aram535** [CiscoPSIRT/openVulnAPI#67]
**Is your feature request related to a problem? Please describe.**
Since the apiconsole.cisco.com portal cannot generate a lifetime token, the examples should contain the "user id", "user secret" authentication method rather than a plain "token" as an authentication method. 
Other language examples, do include the full authentication via id/secret.

**Describe the solution you'd like**
An update to the java client using client id/client secret to obtain a token.

**Comment by santosomar** [comment]
Removing Java Client example, as development efforts will concentrate in the community supported openVulnQuery (Python client).
