### ISSUE TITLE
Please advise whether this API has ability to provide response for the given NX-OS version

### ISSUE THREAD

**Issue by EvgeniNetformx** [CiscoPSIRT/openVulnAPI#70]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by santosomar** [comment]
NX-OS is not yet supported. Cisco is working on supporting NX-OS by the end of this calendar year.

**Comment by abunn-r7** [comment]
Does anyone know when this will be available?

**Comment by santosomar** [comment]
Cisco is working on the NXOS API and should be available in the next couple of months. Although, there is no exact time.

**Comment by santosomar** [comment]
I am pleased to announce that Cisco has released the NXOS Software checker functionality and subsequently, we have added it to the API.

You can query any NX-OS version as such:
```
https://api.cisco.com/security/advisories/nxos?version=8.3(1)
```

The following is an example using `curl` (after using your client credentials to get a token (the token is AAABBBCCC in this example):

```
curl -X GET -s -k -H "Accept: application/json" -H "Authorization: Bearer AAABBBCCC" https://api.cisco.com/security/advisories/nxos?version=8.3(1)
```

**Comment by santosomar** [comment]
To query by NX-OS ACI mode versions use:
```
https://api.cisco.com/security/advisories/aci\?version\=11.0\(2j\) 
```

**Comment by abunn-r7** [comment]
@santosomar Does the update to the API include the data that has been available on the recent CVRFs that indicates which versions are vulnerable when running on certain hardware?
eg:
```
    <Relationship RelatesToProductReference="CVRFPID-265086" RelationType="Installed On" ProductReference="CVRFPID-191447">
      <FullProductName ProductID="CVRFPID-191447:265086">Cisco NX-OS Software 5.2(1) when installed on Cisco MDS 9000 Multilayer Directors and Fabric Switches</FullProductName>
    </Relationship>
    <Relationship RelatesToProductReference="CVRFPID-265088" RelationType="Installed On" ProductReference="CVRFPID-191447">
      <FullProductName ProductID="CVRFPID-191447:265088">Cisco NX-OS Software 5.2(1) when installed on Cisco Nexus 7000 Series Switches</FullProductName>
```
