### ISSUE TITLE
Call API for 12.3(8)T6 IOS includes 2 nodes with NA values

### ISSUE THREAD

**Issue by EvgeniNetformx** [CiscoPSIRT/openVulnAPI#71]
Call for https://api.cisco.com/security/advisories/ios?version=12.3(8)T6 includes 2 nodes with "advisoryId": "cisco-sr-20090114-http" and "advisoryId": "cisco-sr-20081105-vtp" with NA value in almost all fields.
{
			"advisoryId": "cisco-sr-20090114-http",
			"advisoryTitle": "NA",
			"bugIDs": [
				"NA"
			],
			"ipsSignatures": [
				"NA"
			],
			"cves": [
				"NA"
			],
			"cvrfUrl": "NA",
			"ovalUrl": "NA",
			"cvssBaseScore": "NA",
			"cwe": [
				"NA"
			],
			"iosRelease": [
				"12.3(8)T6"
			],
			"firstFixed": [
				"12.4(18e)",
				"12.4(23)"
			],
			"firstPublished": "NA",
			"lastUpdated": "NA",
			"productNames": [
				"NA"
			],
			"publicationUrl": "NA",
			"sir": "NA",
			"summary": "NA"
		},
		{
			"advisoryId": "cisco-sr-20081105-vtp",
			"advisoryTitle": "NA",
			"bugIDs": [
				"NA"
			],
			"ipsSignatures": [
				"NA"
			],
			"cves": [
				"NA"
			],
			"cvrfUrl": "NA",
			"ovalUrl": "NA",
			"cvssBaseScore": "NA",
			"cwe": [
				"NA"
			],
			"iosRelease": [
				"12.3(8)T6"
			],
			"firstFixed": [
				"12.4(18e)",
				"12.4(23)"
			],
			"firstPublished": "NA",
			"lastUpdated": "NA",
			"productNames": [
				"NA"
			],
			"publicationUrl": "NA",
			"sir": "NA",
			"summary": "NA"
		}
Please check. Thanks.

**Comment by santosomar** [comment]
Thank you for reporting this. We are looking into this now. These are very old security advisories. However, they should at least have some of these metadata.

**Comment by santosomar** [comment]
The development team has fixed this issue in the API. This is not an issue in the client.
