### ISSUE TITLE
API Not available in API Console

### ISSUE THREAD

**Issue by JayWelborn** [CiscoPSIRT/openVulnAPI#72]
When creating a new account on Cisco's API Console, the OpenVuln API is not available in the list of My APIs. Are there additional requirements to access the PSIRT API?

**Comment by fwininger** [comment]
Same problem :'(

**Comment by Matthias-vdE** [comment]
Same problem here. If it has been renamed, the readme should be updated.

**Comment by santosomar** [comment]
That is correct. The PSIRT API is only available to Cisco customers and or partners with an active contract. You could contact TAC and see if you could be granted access.
