### ISSUE TITLE
PyPI version of OpenVulnQuery is outdated

### ISSUE THREAD

**Issue by kolatz** [CiscoPSIRT/openVulnAPI#77]
The latest version is dated Oct 16, 2018. It doesn't include the latest commits, especially NX-OS support. Are there any plans to update it?

**Comment by Stjubit** [comment]
Workaround:

`pip3 install -e "git+https://github.com/CiscoPSIRT/openVulnAPI.git#egg=openVulnQuery&subdirectory=openVulnQuery"`

**Comment by kolatz** [comment]
Great! I didn't know that I can specify folder/egg name, etc. Combining with branch name/tag/commit hash, we can describe dependencies precisely. Thank you!
`❯ cat requirements.txt
git+https://github.com/CiscoPSIRT/openVulnAPI.git@588f6e3bfe10ad6a69eebd4c411b3df96bf0e48f#egg=openVulnQuery&subdirectory=openVulnQuery`

**Comment by santosomar** [comment]
The new version of the [openVulnQuery](https://pypi.org/project/OpenVulnQuery/1.31/) Python client has been uploaded to [PyPi](https://pypi.org/project/OpenVulnQuery/1.31/).
You can now use `pip install OpenVulnQuery==1.31` to install the openVulnQuery client.

**Note**: I have also moved the openVulnQuery client code to it's own repository: https://github.com/CiscoPSIRT/openVulnQuery
