### ISSUE TITLE
Get advisories by NXOS version

### ISSUE THREAD

**Issue by VinuraD** [CiscoPSIRT/openVulnAPI#78]
Hi, I came across that there is no method currently available to get advisories by nxos version, in the query_client.py module. Is this a feature that will be added in the future?

***My current alternative solutions** are to (1) make the API calls using requests lib, separately. (without using the Openvulnquery library)
(2) Altering the source codes (have implemented and working, but not tested thoroughly; can make a pull request if its okay)

**Comment by Stjubit** [comment]
I experienced the same issue. The pypi package is not up to date. I overwrote the query_client.py and advisory.py files from the package with the Github source code as a workaround:

/home/<xy>/.local/lib/python3.7/site-packages/openVulnQuery/_library/

...would be very cool to update the pypi package though...

**Comment by Stjubit** [comment]
Another workaround:

`pip3 install -e "git+https://github.com/CiscoPSIRT/openVulnAPI.git#egg=openVulnQuery&subdirectory=openVulnQuery"`

**Comment by santosomar** [comment]
The new version of the [openVulnQuery](https://pypi.org/project/OpenVulnQuery/1.31/) Python client has been uploaded to [PyPi](https://pypi.org/project/OpenVulnQuery/1.31/).
You can now use `pip install OpenVulnQuery==1.31` to install the openVulnQuery client.

**Note**: I have also moved the openVulnQuery client code to it's own repository: https://github.com/CiscoPSIRT/openVulnQuery
