### ISSUE TITLE
Retrieve the Details section of an advisory ?

### ISSUE THREAD

**Issue by TearsOfSky** [CiscoPSIRT/openVulnAPI#79]
Hello,

I use the API to retrieve information from an advisory by parsing the "summary" section of the json output. 

My problem is _sometimes_ I don't have enough information in this section because most of it is stored in the "Details" section of an advisory. Example : https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-ios-webui-priv-esc-K8zvEWM

I can't find a way to retrieve information from this section without using the CVRF.

Do you plan to add this section to the API in the future ?

**Comment by santosomar** [comment]
This is only possible by parsing the CVRF file and there are no plans to include this in the default JSON output. CSAF 2.0 (the new version of CVRF) will be supported in the future, once it is released by the [OASIS CSAF TC](https://oasis-open.github.io/csaf-documentation/).
