### ISSUE TITLE
Product API call didn't work any more

### ISSUE THREAD

**Issue by pixerl0n** [CiscoPSIRT/openVulnAPI#88]
Hello dev team,

since 3 days the API call https://developer.cisco.com/docs/psirt/#!api-reference/querying-by-the-product-name didn't any more. 
I didn't receive for any product a result. It worked before without any issue. Was there a change behind the scenes? 

I'm getting always the result:
```

curl -X GET "https://api.cisco.com/security/advisories/product?product=cisco_xe" or
curl -X GET "https://api.cisco.com/security/advisories/product?product=ASA"

{
    "errorCode": "PRODCUT_NOT_FOUND",
    "errorMessage": "Product not found"
}

```

Thank you & BRgds

**Comment by yparwani** [comment]
Seeing the same issue

**Comment by pixerl0n** [comment]
started working again...
